### ISSUE TITLE
It keeps saying "Could not locate the file of that topic."

### ISSUE THREAD

**Issue by pea-cap** [Friends-of-Monika/mas-wtf#2]
I have no idea why it keeps saying that but here are the submods that I have:
'Discord Presence Submod' v0.4.1,
    'BonkAMon' v0.0.9,
    'Custom Room Kitchen' v1.0.8,
    'Extra Everything' v1.5.0,
    'Submod Updater Plugin' v1.7,
    'Custom Room Den' v1.0.8,
    'Say Something' v1.8.2,
    'Custom Room Garden View' v1.0.6,
    'Open World' v0.2.0,
    'Comfy UI' v2.0.1,
    'NSFW Submod' v1.3.2,
    'Extra Plus' v1.0.9,
    'Where is That From' v1.0.1,
    'Mark as Seen' v1.0.0,
    'Rickroll Monika' v1.0.1,
    'Selector City' v1.0.3,
    'All Gen Scrollable Menus' v1.0.4,
    'Memories of Self Care and Literature' v5.1.2

**Comment by dreamscached** [comment]
See https://github.com/Friends-of-Monika/mas-wtf#-faq

For some users, the game engine doesn't  properly provide internal game info to the submod and without it's impossible to detect the topic. Can you provide more info? What topic are you trying to detect? Is your submod placed in `game` or directly inside `game/Submods`?

**Comment by pea-cap** [comment]
Um nvm I just fixed it by reinstalling the game
